name: pwa_install
description: A Flutter package that allows you to prompt mobile web users to install your Flutter app as a PWA
version: 0.0.6
homepage: https://github.com/jtmuller5/pwa_install

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:

